"""delete message mapping translation channel back populates

Revision ID: 4eb7911bc281
Revises: dc32051ba3b2
Create Date: 2026-01-25 12:16:41.517304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb7911bc281'
down_revision: Union[str, None] = 'dc32051ba3b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
