"""edit guild, translation channel, and message mapping id

Revision ID: b2ef493a928c
Revises: fd2d0ad9f952
Create Date: 2026-01-26 15:32:32.843032

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b2ef493a928c"
down_revision: Union[str, None] = "fd2d0ad9f952"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###  # Changed: remove server_default
    op.execute("DROP SEQUENCE IF EXISTS guilds_id_seq CASCADE")
    op.execute("DROP SEQUENCE IF EXISTS translation_channels_id_seq CASCADE")
    op.alter_column(
        "guilds",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=False,
        server_default=None,
    )
    op.drop_constraint("guilds_guild_id_key", "guilds", type_="unique")
    op.drop_column("guilds", "guild_id")
    op.alter_column(
        "message_mappings",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=False,
        server_default=None,
    )
    op.alter_column(
        "message_mappings",
        "translation_channel_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.drop_column("message_mappings", "guild_id")
    op.alter_column(
        "translation_channels",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=False,
        server_default=None,
    )
    op.alter_column(
        "translation_channels",
        "guild_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.drop_constraint(
        "translation_channels_channel_id_key", "translation_channels", type_="unique"
    )
    op.drop_column("translation_channels", "channel_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SEQUENCE guilds_id_seq")
    op.execute("CREATE SEQUENCE translation_channels_id_seq")
    op.add_column(
        "translation_channels",
        sa.Column(
            "channel_id",
            sa.BIGINT(),
            autoincrement=False,
            nullable=False,
            server_default="0",
        ),
    )
    op.execute("UPDATE translation_channels SET channel_id = id")
    op.alter_column("translation_channels", "channel_id", server_default=None)
    op.create_unique_constraint(
        "translation_channels_channel_id_key",
        "translation_channels",
        ["channel_id"],
        postgresql_nulls_not_distinct=False,
    )
    # op.alter_column(
    #     "translation_channels",
    #     "guild_id",
    #     existing_type=sa.BigInteger(),
    #     type_=sa.INTEGER(),
    #     existing_nullable=False,
    # )
    # op.alter_column(
    #     "translation_channels",
    #     "id",
    #     existing_type=sa.BigInteger(),
    #     type_=sa.INTEGER(),
    #     existing_nullable=False,
    #     autoincrement=False,
    #     existing_server_default=sa.text(
    #         "nextval('translation_channels_id_seq'::regclass)"
    #     ),
    # )
    op.add_column(
        "message_mappings",
        sa.Column("guild_id", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "message_mappings",
        "translation_channel_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "message_mappings",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=False,
    )
    op.add_column(
        "guilds",
        sa.Column(
            "guild_id",
            sa.BIGINT(),
            autoincrement=False,
            nullable=False,
            server_default="0",
        ),
    )
    op.execute("UPDATE guilds SET guild_id = id")
    op.alter_column("guilds", "guild_id", server_default=None)
    op.create_unique_constraint(
        "guilds_guild_id_key",
        "guilds",
        ["guild_id"],
        postgresql_nulls_not_distinct=False,
    )
    # op.alter_column(
    #     "guilds",
    #     "id",
    #     existing_type=sa.BigInteger(),
    #     type_=sa.INTEGER(),
    #     existing_nullable=False,
    #     autoincrement=False,
    #     existing_server_default=sa.text("nextval('guilds_id_seq'::regclass)"),
    # )
    # ### end Alembic commands ###
