"""update guild - translation channel - message mapping relation cascade

Revision ID: b3cbbad73d85
Revises: 4eb7911bc281
Create Date: 2026-01-26 14:47:27.900082

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b3cbbad73d85"
down_revision: Union[str, None] = "4eb7911bc281"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "message_mappings_translation_channel_id_fkey",
        "message_mappings",
        type_="foreignkey",
    )

    op.create_foreign_key(
        "message_mappings_translation_channel_id_fkey",
        "message_mappings",
        "translation_channels",
        ["translation_channel_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "message_mappings_translation_channel_id_fkey",
        "message_mappings",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "message_mappings_translation_channel_id_fkey",
        "message_mappings",
        "translation_channels",
        ["translation_channel_id"],
        ["id"],
    )
    # ### end Alembic commands ###
