"""add guild allow_translation column

Revision ID: b3d1ecbe4ae0
Revises: 06fe3df8602d
Create Date: 2025-08-22 18:21:45.178780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3d1ecbe4ae0'
down_revision: Union[str, None] = '06fe3df8602d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guilds', sa.Column('allow_translation', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guilds', 'allow_translation')
    # ### end Alembic commands ###
