"""add guild_id in message_mapping_model

Revision ID: e7cb399d630b
Revises: b2ef493a928c
Create Date: 2026-01-26 16:26:37.664006

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7cb399d630b"
down_revision: Union[str, None] = "b2ef493a928c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message_mappings", sa.Column("guild_id", sa.BigInteger(), nullable=False)
    )
    op.alter_column(
        "message_mappings",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.execute(
        "ALTER TABLE message_mappings ALTER COLUMN id SET DEFAULT nextval('message_mappings_id_seq'::regclass)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "message_mappings",
        "id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_column("message_mappings", "guild_id")
    op.execute("ALTER TABLE message_mappings ALTER COLUMN id DROP DEFAULT")
    # ### end Alembic commands ###
