"""add created_at and updated_at column

Revision ID: fd2d0ad9f952
Revises: b3cbbad73d85
Create Date: 2026-01-26 15:15:33.819999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd2d0ad9f952'
down_revision: Union[str, None] = 'b3cbbad73d85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guilds', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('guilds', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('message_mappings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('message_mappings', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint('message_mappings_translation_channel_id_fkey', 'message_mappings', type_='foreignkey')
    op.create_foreign_key(None, 'message_mappings', 'translation_channels', ['translation_channel_id'], ['id'])
    op.add_column('translation_channels', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('translation_channels', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translation_channels', 'updated_at')
    op.drop_column('translation_channels', 'created_at')
    op.drop_constraint(None, 'message_mappings', type_='foreignkey')
    op.create_foreign_key('message_mappings_translation_channel_id_fkey', 'message_mappings', 'translation_channels', ['translation_channel_id'], ['id'], ondelete='CASCADE')
    op.drop_column('message_mappings', 'updated_at')
    op.drop_column('message_mappings', 'created_at')
    op.drop_column('guilds', 'updated_at')
    op.drop_column('guilds', 'created_at')
    # ### end Alembic commands ###
